services:
  app:
    build:
      context: .
    container_name: awncert-app
    working_dir: /var/www/html
    volumes:
      - /home/dev-master/celeste/awncert-app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - awncert-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=awncert
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:hS4pGpP0nWEgnJ96Sj85dVwR0EsypWMoNbk1D4a/HVM=
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: awncert-db
    volumes:
      - /home/dev-master/celeste/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: awncert
    networks:
      - awncert-network

networks:
  awncert-network:
    driver: bridge
